In [85]:
import torch
from PIL import Image
import numpy as np
from pathlib import Path

# model = torch.hub.load('ultralytics/yolov5', 'yolov5s', classes=1, autoshape=False, pretrained=False)

state_dict = torch.load('best.pt')

model = state_dict['model']

In [86]:
model = model.type(torch.float32)

In [87]:
img = Image.open(r'raw_data\helvetios_challenge_dataset_training\images\20220915194538484039.png')
img = np.array(img).transpose(2,0,1)
img = torch.tensor(img)
out = model(img.unsqueeze(0).type(torch.float32))

In [88]:
state_dict2 = model.state_dict()
model2 = torch.hub.load('ultralytics/yolov5', 'yolov5s', classes=1, autoshape=True, pretrained=False)

Using cache found in C:\Users\ti-he/.cache\torch\hub\ultralytics_yolov5_master
YOLOv5  2022-11-19 Python-3.10.8 torch-1.13.0+cpu CPU

Overriding model.yaml nc=80 with nc=1

                 from  n    params  module                                  arguments                     
  0                -1  1      3520  models.common.Conv                      [3, 32, 6, 2, 2]              
  1                -1  1     18560  models.common.Conv                      [32, 64, 3, 2]                
  2                -1  1     18816  models.common.C3                        [64, 64, 1]                   
  3                -1  1     73984  models.common.Conv                      [64, 128, 3, 2]               
  4                -1  2    115712  models.common.C3                        [128, 128, 2]                 
  5                -1  1    295424  models.common.Conv                      [128, 256, 3, 2]              
  6                -1  3    625152  models.common.C3                        [2

In [89]:
model2.load_state_dict(state_dict2)

<All keys matched successfully>

In [96]:
img = Image.open(r'raw_data\helvetios_challenge_dataset_training\images\20220915194540522606.png')
img = np.array(img).transpose(2,0,1)
img = torch.tensor(img)
with torch.no_grad():
    out2 = model2(img.unsqueeze(0).type(torch.float32))

In [95]:
model2 = model2.eval()

In [97]:
out2

(tensor([[[ 3.47101e+00,  1.00253e+00,  1.13243e+01,  2.64682e+01,  1.69879e-05,  9.99968e-01],
          [ 6.40485e+00, -6.39384e-01,  1.76613e+01,  1.74468e+01,  1.32448e-06,  9.99984e-01],
          [ 1.27108e+01, -8.38006e-01,  1.08207e+01,  1.92688e+01,  2.89002e-07,  9.99981e-01],
          ...,
          [ 9.40447e+02,  4.94927e+02,  3.74814e+02,  2.93140e+02,  1.33275e-04,  9.99972e-01],
          [ 9.74227e+02,  4.95644e+02,  3.98715e+02,  2.79173e+02,  1.23373e-04,  9.99973e-01],
          [ 1.00613e+03,  4.95906e+02,  4.22962e+02,  3.04555e+02,  1.41448e-04,  9.99978e-01]]]),
 [tensor([[[[[-1.32441e-01, -7.87721e-01,  1.28489e-01,  9.12178e-01, -1.09830e+01,  1.03502e+01],
             [-1.73223e+00, -1.32469e+00,  6.83323e-01,  3.19638e-01, -1.35345e+01,  1.10628e+01],
             [-3.06844e+00, -1.40121e+00,  8.04942e-02,  4.41980e-01, -1.50568e+01,  1.08681e+01],
             ...,
             [-1.95300e+00, -9.96810e-01,  2.42692e-01,  2.07197e-01, -1.46780e+01,  1.0646

In [100]:
for *xyxy, conf in out2:
    print(*xyxy)
    print(conf)


tensor([[ 3.47101e+00,  1.00253e+00,  1.13243e+01,  2.64682e+01,  1.69879e-05,  9.99968e-01],
        [ 6.40485e+00, -6.39384e-01,  1.76613e+01,  1.74468e+01,  1.32448e-06,  9.99984e-01],
        [ 1.27108e+01, -8.38006e-01,  1.08207e+01,  1.92688e+01,  2.89002e-07,  9.99981e-01],
        ...,
        [ 9.40447e+02,  4.94927e+02,  3.74814e+02,  2.93140e+02,  1.33275e-04,  9.99972e-01],
        [ 9.74227e+02,  4.95644e+02,  3.98715e+02,  2.79173e+02,  1.23373e-04,  9.99973e-01],
        [ 1.00613e+03,  4.95906e+02,  4.22962e+02,  3.04555e+02,  1.41448e-04,  9.99978e-01]])
tensor([[[[[-1.32441e-01, -7.87721e-01,  1.28489e-01,  9.12178e-01, -1.09830e+01,  1.03502e+01],
           [-1.73223e+00, -1.32469e+00,  6.83323e-01,  3.19638e-01, -1.35345e+01,  1.10628e+01],
           [-3.06844e+00, -1.40121e+00,  8.04942e-02,  4.41980e-01, -1.50568e+01,  1.08681e+01],
           ...,
           [-1.95300e+00, -9.96810e-01,  2.42692e-01,  2.07197e-01, -1.46780e+01,  1.06468e+01],
           [-2.60